apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emojivoto
bases:
- github.com/BuoyantIO/emojivoto/kustomize/deployment?ref=f1a476f5
patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: emoji
  path: ./auto-inject.json
- target:
    version: v1
    kind: Deployment
    name: voting
  path: ./auto-inject.json
- target:
    version: v1
    kind: Deployment
    name: vote-bot
  path: ./auto-inject.json
- target:
    version: v1
    kind: Deployment
    name: web
  path: ./auto-inject.json
