apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto
  namespace: argocd
spec:
  destination:
    namespace: emojivoto
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: deploy/emojivoto
    repoURL: git://git-server/linkerd2-gitops.git
