apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: demo
  source:
    chart: linkerd2
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.8.0
    helm:
      parameters:
      - name: global.identityTrustAnchorsPEM
        value: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
      - name: installNamespace
        value: "false"
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
