apiVersion: v2
appVersion: edge-20.7.4
description: Linkerd gives you observability, reliability, and security for your microservices
  — with no code change required.
home: https://linkerd.io
icon: https://linkerd.io/images/logo-only-200h.png
keywords:
- service-mesh
kubeVersion: '>=1.13.0-0'
maintainers:
- email: cncf-linkerd-dev@lists.cncf.io
  name: Linkerd authors
  url: https://linkerd.io/
name: linkerd2
sources:
- https://github.com/linkerd/linkerd2/
version: 20.7.4
dependencies:
- name: partials
  version: 0.1.0
  repository: file://../partials
- name: prometheus
  version: 0.1.0
  repository: file://../add-ons/prometheus
  condition: prometheus.enabled
- name: grafana
  version: 0.1.0
  repository: file://../add-ons/grafana
  condition: grafana.enabled
- name: tracing
  version: 0.1.0
  repository: file://../add-ons/tracing
  condition: tracing.enabled
